### ISSUE TITLE
good job  !  thank you

### ISSUE THREAD

**Issue by ghost** [ydomenjoud/ng2-rest-client#1]
:)

we need this project

Please improve it

thank you very much

**Comment by ydomenjoud** [comment]
Hey, thank for your interest. Which feature do you need first ?

**Comment by ghost** [comment]
Thank you for your reply，Server I use is **Django-rest-framework**  http://www.django-rest-framework.org/
in angular1 **https://docs.angularjs.org/api/ngResource** very good，
but **ngResource** not support angular2
Can you transplant it ？

thank you once again
